"""empty message

Revision ID: 72588287b39d
Revises: fb1018aa1977
Create Date: 2022-06-10 13:09:10.961519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72588287b39d'
down_revision = 'fb1018aa1977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
